window.addEventListener('DOMContentLoaded', function() {
    document.querySelector('.section-editions__category-checkbox-list__title').addEventListener('click', function() {       
        document.querySelector('#edition-check-one').classList.toggle('edition-spoiler-active')
        document.querySelector('#edition-check2').classList.toggle('edition-spoiler-active')
        document.querySelector('#edition-check3').classList.toggle('edition-spoiler-active')
        document.querySelector('#edition-check4').classList.toggle('edition-spoiler-active')
        document.querySelector('#edition-check5').classList.toggle('edition-spoiler-active')
        document.querySelector('#edition-check6').classList.toggle('edition-spoiler-active')
        document.querySelector('#edition-check7').classList.toggle('edition-spoiler-active')
        document.querySelector('#edition-check8').classList.toggle('edition-spoiler-active')
        document.querySelector('#edition-check9').classList.toggle('edition-spoiler-active')
        document.querySelector('#edition-check10').classList.toggle('edition-spoiler-active')
        document.querySelector('#edition-check11').classList.toggle('edition-spoiler-active')
        document.querySelector('#edition-check12').classList.toggle('edition-spoiler-active')
    })
  })
